//! Workflow memory shared types.
//!
//! Defines the trait that the agent executor uses to talk to whatever
//! workflow-memory backend the workspace plugin provides. The actual
//! `WorkflowMemoryService` implementation lives in `temps-workspace`, but the
//! `temps-agents` crate consumes it through this trait so we don't need a
//! cyclic dependency.
//!
//! Also defines the bash memory script template that gets installed into
//! every workflow run sandbox. Both the workspace chat and the agent executor
//! use the same script.

use async_trait::async_trait;

/// One memory fact returned by the provider. Mirrors the
/// `temps_entities::workflow_memory::Model` shape but lives in core so the
/// agent executor doesn't need to depend on the entities crate's
/// memory-specific types.
#[derive(Debug, Clone)]
pub struct WorkflowMemoryFact {
    pub id: i64,
    pub fact: String,
    pub confidence: f32,
    pub times_used: i32,
}

/// Errors that can come from a memory provider. Kept opaque so individual
/// implementations can return their own typed errors and we don't have to
/// share an enum across crates.
#[derive(Debug, thiserror::Error)]
#[error("workflow memory error: {message}")]
pub struct WorkflowMemoryError {
    pub message: String,
}

impl WorkflowMemoryError {
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

/// Trait the agent executor uses to read workflow memory before spawning
/// the AI harness. The implementation lives in `temps-workspace` and is
/// injected via the plugin DI registry.
///
/// This trait is intentionally tiny — only what the executor needs at
/// prompt-build time. Memory writes happen via the bash script the AI
/// runs inside the sandbox, not through this trait.
#[async_trait]
pub trait WorkflowMemoryProvider: Send + Sync {
    /// Load the most relevant memory facts for an upcoming run.
    ///
    /// `relevant_tags` is a list of tags derived from the trigger context
    /// (e.g. `["error_group_id:42", "file:src/api/login.ts"]`). The provider
    /// should return facts that match any of those tags, plus a few of the
    /// highest-confidence general facts as a fallback.
    ///
    /// Implementations must enforce strict scoping by `(project_id, agent_id)`
    /// — facts from one workflow must never leak into another.
    async fn load_for_trigger(
        &self,
        project_id: i32,
        agent_id: i32,
        relevant_tags: Vec<String>,
        limit: usize,
    ) -> Result<Vec<WorkflowMemoryFact>, WorkflowMemoryError>;

    /// Render a list of facts as a markdown section to prepend to a prompt.
    /// Returns an empty string for empty input — the caller should never
    /// inject the section header on its own.
    fn render_for_prompt(&self, facts: &[WorkflowMemoryFact]) -> String;
}

// ── Bash memory script template ─────────────────────────────────────────────

/// The path inside the sandbox where the memory script is installed.
pub const MEMORY_SCRIPT_PATH: &str = "/workspace/.temps/bin/memory";

/// The directory inside the sandbox that should be on $PATH so the AI can
/// type `memory write "..."` instead of the full path.
pub const MEMORY_SCRIPT_DIR: &str = "/workspace/.temps/bin";

/// The bash script body. Reads scope from env vars at runtime, so the same
/// script works for any workflow.
///
/// **Required env vars in the sandbox:**
///   - `TEMPS_API_URL` — base URL of the Temps API (defaults to host.docker.internal:3000)
///   - `TEMPS_API_TOKEN` — deployment token scoped to the project
///   - `TEMPS_PROJECT_ID` — project this sandbox is running for
///   - `TEMPS_WORKFLOW_SLUG` — the workflow's slug (so memory is scoped per workflow)
pub const MEMORY_SCRIPT: &str = r#"#!/usr/bin/env bash
# Auto-generated by Temps. Do not edit.
# Workflow memory access for the current Temps workflow.
#
# Usage:
#   memory write "<fact>" [--tags tag1,tag2]
#   memory search "<query>"
#   memory list
#   memory supersede <id> --by "<new fact>"
#
# All operations are scoped to the current workflow via TEMPS_WORKFLOW_SLUG
# and the project via TEMPS_PROJECT_ID.

set -euo pipefail

TEMPS_API_URL="${TEMPS_API_URL:-http://host.docker.internal:3000}"
TEMPS_API_TOKEN="${TEMPS_API_TOKEN:?TEMPS_API_TOKEN not set}"
PROJECT_ID="${TEMPS_PROJECT_ID:?TEMPS_PROJECT_ID not set}"
WORKFLOW_SLUG="${TEMPS_WORKFLOW_SLUG:?TEMPS_WORKFLOW_SLUG not set}"

API_BASE="${TEMPS_API_URL}/api/projects/${PROJECT_ID}/workflows/${WORKFLOW_SLUG}/memory"

CMD="${1:-help}"
shift || true

# Convert a comma-separated tag string to a JSON array via jq.
tags_to_json() {
  if [[ -z "${1:-}" ]]; then
    echo "[]"
  else
    echo "$1" | jq -R 'split(",") | map(select(length > 0))'
  fi
}

case "$CMD" in
  write)
    FACT="${1:-}"
    if [[ -z "$FACT" ]]; then
      echo "usage: memory write \"<fact>\" [--tags tag1,tag2]" >&2
      exit 1
    fi
    shift

    TAGS_JSON="[]"
    if [[ "${1:-}" == "--tags" ]]; then
      shift
      TAGS_JSON=$(tags_to_json "${1:-}")
      shift || true
    fi

    BODY=$(jq -n --arg f "$FACT" --argjson t "$TAGS_JSON" '{fact: $f, tags: $t}')
    RESPONSE=$(curl -sf -X POST "$API_BASE" \
      -H "Authorization: Bearer $TEMPS_API_TOKEN" \
      -H "Content-Type: application/json" \
      -d "$BODY")
    ID=$(echo "$RESPONSE" | jq -r '.id')
    echo "Saved fact #$ID"
    ;;

  search)
    QUERY="${1:-}"
    if [[ -z "$QUERY" ]]; then
      echo "usage: memory search \"<query>\"" >&2
      exit 1
    fi
    curl -sf -G "$API_BASE/search" \
      -H "Authorization: Bearer $TEMPS_API_TOKEN" \
      --data-urlencode "q=$QUERY" \
      --data-urlencode "limit=10" \
    | jq -r '.facts[] | "[\(.id)] (conf=\(.confidence), used=\(.times_used)) \(.fact)"'
    ;;

  list)
    curl -sf "$API_BASE?limit=50" \
      -H "Authorization: Bearer $TEMPS_API_TOKEN" \
    | jq -r '.facts[] | "[\(.id)] (conf=\(.confidence), used=\(.times_used)) \(.fact)"'
    ;;

  supersede)
    ID="${1:-}"
    if [[ -z "$ID" || "${2:-}" != "--by" || -z "${3:-}" ]]; then
      echo "usage: memory supersede <id> --by \"<new fact>\"" >&2
      exit 1
    fi
    NEW_FACT="$3"
    BODY=$(jq -n --arg f "$NEW_FACT" '{new_fact: $f, new_tags: []}')
    curl -sf -X POST "$API_BASE/$ID/supersede" \
      -H "Authorization: Bearer $TEMPS_API_TOKEN" \
      -H "Content-Type: application/json" \
      -d "$BODY"
    echo
    ;;

  help|*)
    cat <<'EOF'
Temps Memory — persistent notes for this workflow.

Usage:
  memory write "<fact>" [--tags tag1,tag2,tag3]
      Save a new finding. Tags help future runs find it.

  memory search "<query>"
      Find past findings matching the query.

  memory list
      Show all current facts for this workflow.

  memory supersede <id> --by "<new fact>"
      Replace an outdated fact with a new one.

Examples:
  memory write "OAuth fails when state cookie missing" --tags error_group_id:42,file:src/api/auth/callback.ts
  memory search "oauth"
  memory list
EOF
    ;;
esac
"#;

/// Build the shell command (suitable for `docker exec`) that installs the
/// memory script in a sandbox container.
pub fn memory_install_command() -> Vec<String> {
    // Use a unique heredoc delimiter that does not appear in the script body.
    let delimiter = "TEMPS_MEMORY_SCRIPT_EOF_X9K2P7";
    let script = format!(
        "mkdir -p {dir} && \
         cat > {path} <<'{delim}'\n{contents}\n{delim}\n\
         chmod +x {path}",
        dir = MEMORY_SCRIPT_DIR,
        path = MEMORY_SCRIPT_PATH,
        delim = delimiter,
        contents = MEMORY_SCRIPT,
    );

    vec!["sh".to_string(), "-c".to_string(), script]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_memory_script_has_required_subcommands() {
        assert!(MEMORY_SCRIPT.contains("write)"));
        assert!(MEMORY_SCRIPT.contains("search)"));
        assert!(MEMORY_SCRIPT.contains("list)"));
        assert!(MEMORY_SCRIPT.contains("supersede)"));
        assert!(MEMORY_SCRIPT.contains("help|*)"));
    }

    #[test]
    fn test_memory_script_reads_required_env_vars() {
        assert!(MEMORY_SCRIPT.contains("TEMPS_API_URL"));
        assert!(MEMORY_SCRIPT.contains("TEMPS_API_TOKEN"));
        assert!(MEMORY_SCRIPT.contains("TEMPS_PROJECT_ID"));
        assert!(MEMORY_SCRIPT.contains("TEMPS_WORKFLOW_SLUG"));
    }

    #[test]
    fn test_memory_script_uses_strict_bash() {
        assert!(MEMORY_SCRIPT.contains("set -euo pipefail"));
    }

    #[test]
    fn test_memory_script_no_cli_dependency() {
        // The script must use curl, NOT a temps CLI binary.
        assert!(MEMORY_SCRIPT.contains("curl"));
        assert!(!MEMORY_SCRIPT.contains("temps memory"));
    }

    #[test]
    fn test_install_command_structure() {
        let cmd = memory_install_command();
        assert_eq!(cmd[0], "sh");
        assert_eq!(cmd[1], "-c");
        let body = &cmd[2];
        assert!(body.contains("mkdir -p /workspace/.temps/bin"));
        assert!(body.contains("chmod +x /workspace/.temps/bin/memory"));
        assert!(body.contains(MEMORY_SCRIPT));
    }

    #[test]
    fn test_install_command_heredoc_delimiter_unique() {
        // The delimiter must NOT appear in the script body or the heredoc
        // would terminate prematurely.
        let cmd = memory_install_command();
        let body = &cmd[2];
        let delim = "TEMPS_MEMORY_SCRIPT_EOF_X9K2P7";
        let count = body.matches(delim).count();
        assert_eq!(
            count, 2,
            "delimiter must appear exactly twice (open + close)"
        );
        assert!(!MEMORY_SCRIPT.contains(delim));
    }

    #[test]
    fn test_workflow_memory_error_construction() {
        let err = WorkflowMemoryError::new("test failure");
        assert_eq!(err.message, "test failure");
        assert!(err.to_string().contains("test failure"));
    }

    #[test]
    fn test_workflow_memory_fact_clone() {
        // The fact type needs to be cheap to clone for prompt rendering.
        let fact = WorkflowMemoryFact {
            id: 1,
            fact: "test fact".to_string(),
            confidence: 0.8,
            times_used: 3,
        };
        let cloned = fact.clone();
        assert_eq!(cloned.id, 1);
        assert_eq!(cloned.fact, "test fact");
        assert_eq!(cloned.confidence, 0.8);
        assert_eq!(cloned.times_used, 3);
    }
}
